AgDaRo/AgDeViagem/Models/Contato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgDeViagem.Models
{
    public class Contato
    {
        [Key]
        public int Id_Contato { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public String Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public int Senha { get; set; }
        public virtual List<Contato> contato { get; set; }
    }
}

AgDaRo/AgDeViagem/Models/Passagem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AgDeViagem.Models
{
    public class Passagem
    {
        [Key]
        public int Id_Passagem { get; set; }
        public string Destino { get; set; }
        public DateTime Data_Ida { get; set; }
        public DateTime Data_Volta { get; set; }
        public string Valor { get; set; }
        [ForeignKey("Contato")]
        public int Id_Contato { get; set; }
        public virtual Contato contato { get; set; }
        [ForeignKey ("Promoção")]
        public int Id_Promoção { get; set; }
        public virtual Promoção promoção { get; set; }

        public string imgPassagem { get; set; }


    }
}

AgDaRo/AgDeViagem/Models/Promoção.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgDeViagem.Models
{
    public class Promoção
    {
        [Key]
        public int Id_Promoção { get; set; }
        public string Desconto { get; set; }
        public string Valor_Final { get; set; }
        public virtual List<Contato> contato { get; set; }

    }
}

AgDaRo/AgDeViagem/Controllers/HomeController.cs
using AgDeViagem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AgDeViagem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contato()
        {
            return View();
        }

        public IActionResult Passagem
            ()
        {
            return View();
        }

        public IActionResult Promoção
            ()
        {
            return View();
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgDaRo/AgDeViagem/Controllers/PassagemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgDeViagem.Models;

namespace AgDeViagem.Controllers
{
    public class PassagemsController : Controller
    {
        private readonly Context _context;

        public PassagemsController(Context context)
        {
            _context = context;
        }

        // GET: Passagems
        public async Task<IActionResult> Index()
        {
            return View(await _context.passagens.ToListAsync());
        }

        // GET: Passagems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passagem = await _context.passagens
                .FirstOrDefaultAsync(m => m.Id_Passagem == id);
            if (passagem == null)
            {
                return NotFound();
            }

            return View(passagem);
        }

        // GET: Passagems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Passagems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Passagem,Destino,Data_Ida,Data_Volta,Valor,Id_Contato,Id_Promoção,imgPassagem")] Passagem passagem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(passagem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(passagem);
        }

        // GET: Passagems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passagem = await _context.passagens.FindAsync(id);
            if (passagem == null)
            {
                return NotFound();
            }
            return View(passagem);
        }

        // POST: Passagems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Passagem,Destino,Data_Ida,Data_Volta,Valor,Id_Contato,Id_Promoção,imgPassagem")] Passagem passagem)
        {
            if (id != passagem.Id_Passagem)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(passagem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PassagemExists(passagem.Id_Passagem))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(passagem);
        }

        // GET: Passagems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passagem = await _context.passagens
                .FirstOrDefaultAsync(m => m.Id_Passagem == id);
            if (passagem == null)
            {
                return NotFound();
            }

            return View(passagem);
        }

        // POST: Passagems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var passagem = await _context.passagens.FindAsync(id);
            _context.passagens.Remove(passagem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PassagemExists(int id)
        {
            return _context.passagens.Any(e => e.Id_Passagem == id);
        }
    }
}

AgDaRo/AgDeViagem/Controllers/PromoçãoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgDeViagem.Models;

namespace AgDeViagem.Controllers
{
    public class PromoçãoController : Controller
    {
        private readonly Context _context;

        public PromoçãoController(Context context)
        {
            _context = context;
        }

        // GET: Promoção
        public async Task<IActionResult> Index()
        {
            return View(await _context.promoções.ToListAsync());
        }

        // GET: Promoção/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promoção = await _context.promoções
                .FirstOrDefaultAsync(m => m.Id_Promoção == id);
            if (promoção == null)
            {
                return NotFound();
            }

            return View(promoção);
        }

        // GET: Promoção/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Promoção/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Promoção,Desconto,Valor_Final")] Promoção promoção)
        {
            if (ModelState.IsValid)
            {
                _context.Add(promoção);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(promoção);
        }

        // GET: Promoção/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promoção = await _context.promoções.FindAsync(id);
            if (promoção == null)
            {
                return NotFound();
            }
            return View(promoção);
        }

        // POST: Promoção/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Promoção,Desconto,Valor_Final")] Promoção promoção)
        {
            if (id != promoção.Id_Promoção)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promoção);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromoçãoExists(promoção.Id_Promoção))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promoção);
        }

        // GET: Promoção/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promoção = await _context.promoções
                .FirstOrDefaultAsync(m => m.Id_Promoção == id);
            if (promoção == null)
            {
                return NotFound();
            }

            return View(promoção);
        }

        // POST: Promoção/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var promoção = await _context.promoções.FindAsync(id);
            _context.promoções.Remove(promoção);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PromoçãoExists(int id)
        {
            return _context.promoções.Any(e => e.Id_Promoção == id);
        }
    }
}

AgDaRo/AgDeViagem/Views/Home/Contato.cshtml
@{
    ViewData["Title"] = "E lá vamos Nós";
}
<h1>@ViewData["Title"]</h1>

<p>Coloque seus dados que entraremos em contato com você.</p>

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title> Agencia de Viagens </title>
</head>

<body>

    <h2>Seja bem vindo (a)</h2>

    <p>Vem Viajar com a <strong> gente!</p></strong>
    <p>Vem Viajar com a <em> gente!</p></em>



    <br>
    <h4> Viagem dos Sonhos.</h4>
    </br>


    <table class="table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Senha</th>

            </tr>


    </table>

    <form>
        <label for="nome">Nome:</label>
        <input id="nome" type="text">

        <label for="CPF">CPF:</label>
        <input id="PF" type="number">

        <label for="email">Email:</label>
        <input id="email" type="text">

        <label for="Senha">Senha:</label>
        <input id="Senha" type="text">

        
        <button id="botaoEnviar">Enviar</button>
    </form>


</body>



</html>

AgDaRo/AgDeViagem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="HomeBanner">
    <h1>Planeje sua viagem com comodidade!</h1>
    <a class="btn btn-danger" asp-controller="Passagems" asp-action="Index">Destinos</a>
</div>

AgDaRo/AgDeViagem/Views/Home/Passagem.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title> Agencia de Viagens </title>
</head>

<body>

    <h2>Seja bem vindo (a)</h2>

    <p>Vem Viajar com a <strong> gente!</p></strong>
    <p>Vem Viajar com a <em> gente!</p></em>


    <br>
    <h4> Viagem dos Sonhos.</h4>
    </br>

    <br>
    <h5>Afinal, pra que ir pra Maldivas, se eu posso me divertir no alfalto de SP/ES/MG</h5>
    </br>





    <table class="table">
        <thead>
            <tr>
                <th "São Paulo">São Paulo</th>
                <th "Espirito Santo">Espirito Santo</th>
                <th "Minas Gerais">Minas Gerais</th>

            </tr>
        </thead>

        <tr>
            <
            <td>R$ 1.500,00</td>
            <td>R$ 2.000,00</td>
            <td>R$ 3.000,00</td>
        </tr>

        <tr>

            <td>Ar Fresco</td>
            <td>Sem Vioência</td>
            <td>Muitas Praias</td>
        </tr>

    </table>

    <form>
        <label for="Destino">Destino:</label>
        <input id="Destino" type="text">

        <label for="Data Ida">Data Ida:</label>
        <input id="Data Ida" type="date">

        <label for="Data Volta">Data Volta:</label>
        <input id="Data Volta" type="date">

        <label for="Valor">Valor:</label>
        <input id="Valor" type="number">


        <button id="botaoEnviar">Enviar</button>
    </form>


</body>



</html>

AgDaRo/AgDeViagem/Views/Home/Promoção.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title> Agencia de Viagens </title>
</head>

<body>

    <h2>Seja bem vindo (a)</h2>

    <p>Vem Viajar com a <strong> gente!</p></strong>
    <p>Vem Viajar com a <em> gente!</p></em>

    <br>
    <a href="Index.html">Home</a>
    </br>

    <br>
    <a href="Destino.html">Destino</a>
    </br>

    <br>
    <a href="Promoções.html">Promoções</a>
    </br>

    <br>
    <a href="Contato.html">Contato</a>
    </br>

    <br>
    <h4> Viagem dos Sonhos.</h4>
    </br>

    <br>
    <h5>Afinal, pra que ir pra Maldivas, se eu posso me divertir no alfalto de SP/ES/MG</h5>
    </br>





    <table class="table">
        <thead>
            <tr>
                <th "São Paulo">São Paulo</th>
                <th "Espirito Santo">Espirito Santo</th>
                <th "Minas Gerais">Minas Gerais</th>

            </tr>
        </thead>

        <tr>
            <
            <td>10%</td>
            <td>10%</td>
            <td>10%</td>
        </tr>

        <tr>

            <td>Cupom: SP10</td>
            <td>Cupom: ES10</td>
            <td>Cupom: MG10</td>
        </tr>

    </table>


</body>



</html>